# Generated by Django 4.0.4 on 2022-05-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=30)),
                ('Emp_Id', models.IntegerField()),
                ('email', models.EmailField(default=True, max_length=40)),
                ('gender', models.CharField(default=True, max_length=12)),
                ('Address', models.CharField(default=True, max_length=100)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lakshmana.dept')),
            ],
        ),
    ]
